print("My name is Ibrahim Durosinmi")
print("I learned about the basics of computer programming in COSC 1436.")
print("I gained knowledge of the Python programming language.")
print("I worked on various projects involving algorithms and data structures.")
print("I developed skills in problem-solving and critical thinking.")
print("I participated in coding challenges and hackathons.")
print("I learned about different software development methodologies.")
print("I improved my ability to work in a team environment.")
print("I was exposed to different software tools and technologies.")
print("I was able to apply what I learned to real-world projects.")
print("I have a better understanding of the role of computer science in society.")
